#!/usr/bin/env -S deno run --allow-read --allow-write

/* global Deno */

import { expandGlob } from "jsr:@std/fs";
import { isGlob } from "jsr:@std/path";
import { DOMParser } from "jsr:@b-fuze/deno-dom";
import packageInfo from "./deno.json" with { type: "json" };

import { initDependencies, main } from "./mod.js";

const { args, readFile, writeTextFile, exit } = Deno;
initDependencies({ expandGlob, isGlob, DOMParser, args, readFile, writeTextFile, exit, moduleVersion: packageInfo.version });
await main();