#!/usr/bin/env -S deno run --allow-read --allow-write --allow-net

/* global Deno */

import { expandGlob } from "jsr:@std/fs";
import { isGlob } from "jsr:@std/path";
import { DOMParser } from "jsr:@b-fuze/deno-dom";

import { initDependencies, main } from "./mod.js";

const { args, readTextFile, writeTextFile, exit } = Deno;
initDependencies({ expandGlob, isGlob, DOMParser, args, readTextFile, writeTextFile, exit });
await main();